# Generated by Django 4.1.4 on 2022-12-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpage',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userpage',
            name='ratings',
        ),
    ]
