
console.log("\n")
console.log("Bernstein 3 3")
let bern = new Bernstein(3,3)
console.log("Vrednost pri 0.5 je "+bern.value(0.5))
console.log("Odvod pri 0.5 je "+bern.derivative(0.5))
console.log("\n")
console.log("Bernstein 2 3")
bern = new Bernstein(2,3)
console.log("Vrednost pri 0.5 je "+bern.value(0.5))
console.log("Odvod pri 0.5 je "+bern.derivative(0.5))
