#cloud-config

hostname: vm-front
source_image: ubuntu-20-04-lts

package_update: true
package_upgrade: true


#ssh_authorized_keys:
#  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDA4H1F1TxVfYc/FrbDZ5S8s9dFy0SPPfp52MSFbkvoIqZjjM9TvlNa4kclQAIdWdJJ4QCVS8x4hOE3pnSC26VR1a+iA+WBGW4XyTpy1oGWBjYhfmFFU6viYIAiXZZLaN65AfFhWR1hTf/5Ib2dWV9xw4gwSykfKQ3+vibcleBZt5To0fHAbvn3qumly3Zup4s3MxvYaulr6CkH6HkHKFaohcQ0//A7CWjo7sOaxxsUNVvgnkvyySoNPfypEHFxNqdAIgXCAI6buDXON/mHIQY2fbraOBYeIjCz9J6RVviWhCVPz/mrKfF9nmvlDcX4QDr832fxh71GyvNcdYSLcbhP4XqWc05R3O9ANt3UtCUmq4YDmJsyR9+3UmqMjzQ4xIa+N9lYAjS8z48CvsXNLuN4xSj6Zkhmt2lfGZx+kE/8hTb2lVxy3EUyyx0VOBQGM7LIBIaIy9hqhLR8PtWdhS0RcZz4z37mP1OnOVhzdptbrUXA7P7SROkB31zmAC5Hb7CqR8wcpCXQnmgqHnQIETKNeXw9KrPY+Zc+ZsvOpz8n4uRxxjlgsNNYmRwTO5edlI4wB10gUO5PrwpSxRDcxv4LUPR7h2M0UwGGc2dWSJAq9r1FywHEpVlF5gU03SGbbm7rh2MiujrHG6lcBog0RunEgxGmmEy2WALZIoDg01Cw/Q== mr.slairy@gmail.com

#hostname: nodejs-frontend

#ssh_import_id:
#  - github: mr.slairy@gmail.com
  

packages:
  #- sudo
  - git
  - nodejs

write_files:
  - path: /front/  
    content: |
      app.js
      generateMeme.html
      index.html
      userPage.html
        
#$(tar -czvf - /path/on/local/folder | base64 -w0)

runcmd:
  - sudo apt-get update && apt-get upgrade -y
  - sudo apt-get install install nodejs -y
  - node server.js